apiVersion: v1
kind: ServiceAccount
metadata:
  name: btpsa-service-account
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: btpsa-role
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
      - gateway.kyma-project.io
      - servicecatalog.k8s.io
      - serverless.kyma-project.io
      - servicecatalog.kyma-project.io
      - services.cloud.sap.com
    resources:
      - deployments
      - replicasets
      - pods
      - jobs
      - configmaps
      - apirules
      - serviceinstances
      - servicebindings
      - servicebindingusages
      - services
      - secrets
      - namespaces
      - functions
    verbs:
      - create
      - update
      - patch
      - delete
      - get
      - list
