#!/usr/bin/env bash

NOCOLOR='\033[0m'
GREEN='\033[0;32m'

thisname="btp-setup-automator"

echo -e "${GREEN}Cleaning up containers and images (if existing)${NOCOLOR}"
docker container stop   "${thisname}"
docker container rm  -f "${thisname}"
docker image     rmi -f "${thisname}"


if [ "$1" != "RunFromRegistry" ]; then
    
    echo -e "${GREEN}Building the container image ...${NOCOLOR}"
    docker image build -t ${thisname}:latest -f "config/Dockerfile"  .

    echo -e "${GREEN}Start the container as '${thisname}' - Access possible e.g. via VSCode${NOCOLOR}"
    docker container run -e BTPSA_VERSION_GIT="$(git describe --long --tags  --always)" --rm -it -d --name "${thisname}" "${thisname}" 

else

    echo -e "${GREEN}Pulling container image from registry ...${NOCOLOR}"
    docker pull ghcr.io/sap-samples/btp-setup-automator:main

    echo -e "${GREEN}Start the container as '${thisname}' - Access possible e.g. via VSCode${NOCOLOR}"
    docker container run --rm  -it -d --name "${thisname}" ghcr.io/sap-samples/btp-setup-automator:main 

fi
