#!/usr/bin/env bash

NOCOLOR='\033[0m'
GREEN='\033[0;32m'

thisname="btp-setup-automator"

echo -e "${GREEN}Cleaning up containers and images (if existing)${NOCOLOR}"
docker container stop   "${thisname}"
docker container rm  -f "${thisname}"
docker image     rm  -f "${thisname}"

echo -e "${GREEN}Building the image ...${NOCOLOR}"
docker image build -t ${thisname}:latest -f "config/Dockerfile"  .

echo -e "${GREEN}Starting the container as '${thisname}' - Access possible e.g. via VS Code${NOCOLOR}"
BTPSA_VERSION_GIT=$(git describe --long --tags --always) \
  docker compose -f config/docker-compose.yaml up -d
