#! /usr/bin/env python
from libs.python.helperGenerator import BTPUSECASE_GEN

UPDATE_SERVICE_DATA = True

mainDataJsonFile = "./config/btp-base/btpServices.json"
#######################################################################################
# Initialize the tool and fetch the BTP service list
#######################################################################################
generator = BTPUSECASE_GEN()
generator.fetchEntitledServiceList(UPDATE_SERVICE_DATA, mainDataJsonFile)

#######################################################################################
# Generate all files
#######################################################################################
if UPDATE_SERVICE_DATA:
    targetFilename = mainDataJsonFile
    templateFile = "./config/templates/btp-base/BTPSERVICES.json"
    generator.applyServiceListOnTemplate(templateFile, targetFilename)

targetFilename = "./docs/gh-pages/btp-services-docs.md"
templateFile = "./config/templates/docs-gh-pages/BTP-SERVICES-DOCS.md"
generator.applyServiceListOnTemplate(templateFile, targetFilename)

targetFilename = "./libs/btpsa-usecase.json"
templateFile = "./config/templates/libs/BTPSA-USECASE.json"
generator.applyServiceListOnTemplate(templateFile, targetFilename)

targetFilename = "./libs/btpsa-parameters.json"
templateFile = "./config/templates/libs/BTPSA-PARAMETERS.json"
generator.applyServiceListOnTemplate(templateFile, targetFilename)
