#! /usr/bin/env python
from libs.python.helperGenerator import BTPUSECASE_GEN

#######################################################################################
# Initialize the tool and fetch the BTP service list
#######################################################################################
generator = BTPUSECASE_GEN()
generator.fetchEntitledServiceList()
generator.addSchemaInfoToServiceList()
generator.addNumSection()


#######################################################################################
# Initialize the tool
#######################################################################################
targetFilename = "./config/btp-base/entitledServices.json"
templateFile = "ENTITLEDSERVICES.json"
generator.applyServiceListOnTemplate(targetFilename, templateFile)
