#! /usr/bin/env python
from libs.python.helperJsonSchemas import buildJsonSchemaFile
from libs.python.helperJson import getJsonFromFile

# Run this command in the command line to get all options of this script
# ./btpsa -h

# This file needs to be deleted prior the PR
list = getJsonFromFile(None, "libs/json/list.json")

buildJsonSchemaFile("btpsa_usecases.json", "btpsa_usecase_new.json", list)
buildJsonSchemaFile("btpsa_parameters.json", "btpsa_parameters_new.json", list)
